name: precise_place_picker
description: Place picker inspired from place_picker which returns autocomplete suggestion data with Localization.
version: 0.0.1-nullsafety
homepage: https://github.com/TimothyGCY/precise_location_picker

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  google_maps_flutter: ^2.1.1
  http: ^0.13.4
  location: ^4.3.0
  uuid: ^3.0.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0

flutter:
